### ISSUE TITLE
I want to use the Person detector App, but the screen remains dark.

### ISSUE THREAD

**Issue by Shotaro-N** [paulald/loomo-algodev-mirror-paul-elevator#2]
Hello, paulald.
Thank you for the other day.
TensorFlow sample App worked well.

But a project that is close to what I want to do is the person detection App you created.

I put ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb with "adb push" and execute it like TensorFlow sample App, but the screen remains black.
Sorry for the solution hint.
Also, did you retrain with a custom dataset?

I'm sorry again and again, but thank you.
Thank you.

**Comment by Shotaro-N** [comment]
I changed the model and it worked
Thank you

**Comment by paulald** [comment]
No I did not retrain with a custom dataset by the way
